### ISSUE TITLE
unpack_test.go:169: unexpected UnpackManifest error: operation not supported

### ISSUE THREAD

**Issue by ganto** [opencontainers/umoci#235] opened 2018-04-10 06:20 UTC
I was trying to write a Fedora/EPEL RPM spec for `umoci`. When building it with `mock` the `%check` step fails with the following error:
```
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.YXKXST                                                                                                          
+ umask 022                                                                         
+ cd /builddir/build/BUILD                                        
+ cd umoci-0.4.0
++ pwd
+ export GOPATH=/builddir/build/BUILDROOT/umoci-0.4.0-0.1.el7.centos.x86_64//usr/share/gocode:/builddir/build/BUILD/umoci-0.4.0/Godeps/_workspace:/usr/share/gocode
+ GOPATH=/builddir/build/BUILDROOT/umoci-0.4.0-0.1.el7.centos.x86_64//usr/share/gocode:/builddir/build/BUILD/umoci-0.4.0/Godeps/_workspace:/usr/share/gocode        
+ go test github.com/openSUSE/umoci/...                                                                                                                        
ok      github.com/openSUSE/umoci/cmd/umoci     0.004s                                                                                                                    
ok      github.com/openSUSE/umoci/mutate        0.218s                                                                                                         
?       github.com/openSUSE/umoci/oci/cas       [no test files]                                                                                                           
ok      github.com/openSUSE/umoci/oci/cas/dir   0.016s                                                                                                         
ok      github.com/openSUSE/umoci/oci/casext    3.767s                                                                                                         
?       github.com/openSUSE/umoci/oci/config/convert    [no test files]
ok      github.com/openSUSE/umoci/oci/config/generate   0.007s
2018/04/09 18:16:15  warn generate layer: could not add file 'some/parents/filechanged': add file lstat: lstat /tmp/umoci-TestGenerateError341961064/some/parents/filechanged: no such file or directory                                                                                                                           
2018/04/09 18:16:15  warn generate layer: could not add file 'some/parents': add file lstat: lstat /tmp/umoci-TestGenerateError162655143/some/some/parents: no such file or directory
2018/04/09 18:16:15  info unpack layer: sha256:159fc03d42b1eb2588cdffaabe13b9a4b25879d64db0ea473c6c411adcc5740a
--- FAIL: TestUnpackManifestCustomLayer (0.00s)
        unpack_test.go:169: unexpected UnpackManifest error: operation not supported
                unpriv.lsetxattr
                github.com/openSUSE/umoci/pkg/unpriv.Lsetxattr
                        /builddir/build/BUILDROOT/umoci-0.4.0-0.1.el7.centos.x86_64/usr/share/gocode/src/github.com/openSUSE/umoci/pkg/unpriv/unpriv.go:490
                github.com/openSUSE/umoci/pkg/fseval.unprivFsEval.Lsetxattr
                        /builddir/build/BUILDROOT/umoci-0.4.0-0.1.el7.centos.x86_64/usr/share/gocode/src/github.com/openSUSE/umoci/pkg/fseval/fseval_rootless.go:127
                github.com/openSUSE/umoci/pkg/fseval.(*unprivFsEval).Lsetxattr
                        <autogenerated>:40
                github.com/openSUSE/umoci/oci/layer.(*tarExtractor).restoreMetadata
                        /builddir/build/BUILDROOT/umoci-0.4.0-0.1.el7.centos.x86_64/usr/share/gocode/src/github.com/openSUSE/umoci/oci/layer/tar_extract.go:136
                github.com/openSUSE/umoci/oci/layer.(*tarExtractor).applyMetadata
                        /builddir/build/BUILDROOT/umoci-0.4.0-0.1.el7.centos.x86_64/usr/share/gocode/src/github.com/openSUSE/umoci/oci/layer/tar_extract.go:167
                github.com/openSUSE/umoci/oci/layer.(*tarExtractor).unpackEntry
                        /builddir/build/BUILDROOT/umoci-0.4.0-0.1.el7.centos.x86_64/usr/share/gocode/src/github.com/openSUSE/umoci/oci/layer/tar_extract.go:489
                github.com/openSUSE/umoci/oci/layer.UnpackLayer
                        /builddir/build/BUILDROOT/umoci-0.4.0-0.1.el7.centos.x86_64/usr/share/gocode/src/github.com/openSUSE/umoci/oci/layer/unpack.go:67
                github.com/openSUSE/umoci/oci/layer.UnpackManifest
                        /builddir/build/BUILDROOT/umoci-0.4.0-0.1.el7.centos.x86_64/usr/share/gocode/src/github.com/openSUSE/umoci/oci/layer/unpack.go:225
                github.com/openSUSE/umoci/oci/layer.TestUnpackManifestCustomLayer
                        /builddir/build/BUILDROOT/umoci-0.4.0-0.1.el7.centos.x86_64/usr/share/gocode/src/github.com/openSUSE/umoci/oci/layer/unpack_test.go:168
                testing.tRunner
                        /usr/lib/golang/src/testing/testing.go:657
[...]
FAIL
FAIL    github.com/openSUSE/umoci/oci/layer     0.076s
error: Bad exit status from /var/tmp/rpm-tmp.gNOTQZ (%check)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.YXKXST (%check)
ERROR: Exception(SRPMS/umoci-0.4.0-0.1.el7.centos.src.rpm) Config(epel-7-x86_64) 0 minutes 54 seconds
INFO: Results and/or logs in: /var/lib/mock/epel-7-x86_64/result
ERROR: Command failed: 
 # /usr/bin/systemd-nspawn -q -M 74acf18b195c4d7b87af0a6f55d43603 -D /var/lib/mock/epel-7-x86_64/root -a --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=en_US.utf8 -u mockbuild bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/umoci.spec
```
The same error happens for a EPEL-7 chroot with `golang-1.8.3-1.el7.x86_64` and a Fedora 27 chroot with `golang-1.9.4-2.fc27.x86_64`. The build host is a Fedora 26 with `mock-1.4.9-1.fc26.noarch`.

In the issues I found #49 which might be somehow related. On the other hand I experienced a similar error (rpm-software-management/librepo#119) where I assumed the tmpfs used for the test files at `/tmp` is at fault.

As it seems you are aware of any "special" behavior regarding xattrs on the RHEL-family of operating systems, could you help me to figure out what's the issue here?

**Comment by cyphar** [comment] 2018-04-10 06:38
The main xattr-related issue that you could see would be from SELinux (because SELinux stores file labels in the `security.selinux` xattr). However, `umoci` intentionally ignores that xattr because of the issues it's known to cause (if you try to touch it without knowing that it's SELinux related you will get all sorts of errors). So I'm not convinced this is an SELinux issue (especially since it happens in a test).

**But** you can get `ENOTSUP` if you are running on a filesystem (like AUFS) that doesn't fully support xattrs. Docker has some workarounds for this issue, and I didn't include them because they are quite hacky and don't really work all that much. What filesystem are you running the tests on (and what filesystem is `/tmp`)?

**Comment by ganto** [comment] 2018-04-10 06:46
It's a regular `mock` build, with the root file system being ext4 and `/tmp` being a tmpfs. Here the mount output from within the build environment:
```
<mock-chroot> sh-4.2# mount                                                                                                                                               
/dev/mapper/vg_system-+mock.epel--7--x86_64.head on / type ext4 (rw,relatime,seclabel,stripe=16,data=ordered)                                                             
/dev/mapper/luks-a0c4d069-c089-40e7-8a44-f443391de155 on /var/cache/yum type ext4 (rw,nosuid,nodev,noatime,seclabel,stripe=16,data=ordered)                               
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,seclabel)                                  
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime,seclabel)                                                                                                       
selinuxfs on /sys/fs/selinux type selinuxfs (ro,nosuid,nodev,noexec,relatime)        
tmpfs on /dev type tmpfs (rw,nosuid,seclabel,mode=755)                                                                                                                    
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,seclabel)                                                                                                                   
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=666)                                                                           
devpts on /dev/console type devpts (rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=000)                                                                       
tmpfs on /run type tmpfs (rw,nosuid,nodev,seclabel,mode=755)                         
tmpfs on /run/systemd/nspawn/incoming type tmpfs (ro,seclabel,mode=755)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
proc on /proc/sys type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/sysrq-trigger type proc (ro,nosuid,nodev,noexec,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,seclabel,mode=755)
cgroup on /sys/fs/cgroup/devices type cgroup (ro,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/pids type cgroup (ro,nosuid,nodev,noexec,relatime,pids)
```

What just came to my mind... The build doesn't really run in a real chroot but in a `systemd-nsspawn` sandbox. Might this be something that influences the xattr behavior?

**Comment by cyphar** [comment] 2018-04-10 08:09
I'm not entirely sure but I will play around with it a bit. The test that is failing (can you confirm if that is the only test failing) is actually not meant to be testing the filesystem at all -- it just tests that layers created using `tar` (manually) still work with `umoci`. So it's possible there's something broken inside the archive I've created that only gets hit with your setup. I'm going to try to reproduce it -- can you give me a quick snippet of how to use `mock` to reproduce the issue (outside of an `rpmbuild`)?

> What just came to my mind... The build doesn't really run in a real chroot but in a systemd-nsspawn sandbox. Might this be something that influences the xattr behavior?

It shouldn't. `umoci` should work perfectly fine inside containers.

**Comment by ganto** [comment] 2018-04-10 17:17
> I'm going to try to reproduce it -- can you give me a quick snippet of how to use mock to reproduce the issue (outside of an `rpmbuild`)?

[Here](https://gist.github.com/ganto/ef8c45b0bbc99c515e7c9015a292bcca) is my spec file (uncomment the failing test to reproduce the issue) and my [mock](https://gist.github.com/ganto/fabfc2191692e92596085ed146f2c671)  configuration (nothing special here). Then I have a directory structure like:
```
umoci/
├── RPMS
├── SOURCES
│   └── umoci-0.4.0.tar.gz
├── SRPMS
└── umoci.spec
``` 
The build command from within the directory, something like:
```
mock -r epel-7-x86_64 --init
mock -r epel-7-x86_64 --buildsrpm --spec umoci.spec --sources SOURCES/ && \
mock -r epel-7-x86_64 --copyout --no-cleanup-after /builddir/build/SRPMS/*.src.rpm SRPMS/ && \
mock -r epel-7-x86_64 --rebuild SRPMS/*.src.rpm && \
mock -r epel-7-x86_64 --copyout /builddir/build/RPMS/*.rpm RPMS/
```

**Comment by ganto** [comment] 2018-04-11 16:54
I just tried to build the package on COPR ([ganto/umoci: build 739919](https://copr.fedorainfracloud.org/coprs/ganto/umoci/build/739919/)) but no matter what Fedora release or architecture, the mentioned error is always be triggered.

**Comment by cyphar** [comment] 2018-09-03 18:45
This should be fixed by #252.

**Comment by ganto** [comment] 2018-09-04 19:20
I tried to build commit cf5aef8ca6fbbdf0d4f8f58bb43d7add48f171a6 now there is another error:
```
ok      github.com/openSUSE/umoci/oci/config/generate   0.003s                                                                                                           
+ go test -buildmode pie -compiler gc -ldflags ' -extldflags '\''-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '\''' github.com/openSUSE/umoci/oci/layer    
2018/09/04 21:13:34  warn generate layer: could not add file 'some/parents/filechanged': add file lstat: lstat /tmp/umoci-TestGenerateError661758941/some/parents/filechanged: no such file or directory                                                                                                                                           
2018/09/04 21:13:34  warn generate layer: could not add file 'some/parents': add file lstat: lstat /tmp/umoci-TestGenerateError067136920/some/some/parents: no such file or directory                                                                                                                                                              
--- FAIL: TestUnpackEntrySanitiseScoping (0.00s)
        tar_extract_test.go:118: running TestGarbagePrefix
        tar_extract_test.go:73: unexpected UnpackEntry error: restore parent directory: restore xattr metadata: saw forbidden xattr "security.selinux": rootfs/
--- FAIL: TestUnpackEntrySymlinkScoping (0.00s)
        tar_extract_test.go:157: running TestRootPrefix
        tar_extract_test.go:73: unexpected UnpackEntry error: restore parent directory: restore xattr metadata: saw forbidden xattr "security.selinux": rootfs/
--- FAIL: TestUnpackEntryWhiteout (0.00s)
        tar_extract_test.go:228: running TestFileInRoot
        tar_extract_test.go:283: unexpected error in UnpackEntry: restore parent directory: restore xattr metadata: saw forbidden xattr "security.selinux": umoci-TestUnpackEntryWhiteout448607820/
2018/09/04 21:13:34  warn rootless{test-subdir/} ignoring forbidden xattr: "security.selinux"
2018/09/04 21:13:34  warn rootless{test-subdir/} ignoring forbidden xattr: "security.selinux"
2018/09/04 21:13:34  warn rootless{test-subdir/} ignoring forbidden xattr: "security.selinux"
2018/09/04 21:13:34  warn rootless{test-subdir/} ignoring forbidden xattr: "security.selinux"
2018/09/04 21:13:34  warn rootless{test-subdir/} ignoring forbidden xattr: "security.selinux"
2018/09/04 21:13:34  warn rootless{test-subdir/} ignoring forbidden xattr: "security.selinux"
2018/09/04 21:13:34  warn rootless{test-subdir/} ignoring forbidden xattr: "security.selinux"
2018/09/04 21:13:34  warn rootless{test-subdir/} ignoring forbidden xattr: "security.selinux"
2018/09/04 21:13:34  warn rootless{test-subdir/} ignoring forbidden xattr: "security.selinux"
[...]
2018/09/04 21:13:34  warn rootless{test-subdir/} ignoring forbidden xattr: "security.selinux"                                                                            
--- FAIL: TestUnpackHardlink (0.00s)                                                                                                                                     
        tar_extract_test.go:615: regular: unexpected UnpackEntry error: restore parent directory: restore xattr metadata: saw forbidden xattr "security.selinux": umoci-TestUnpackHardlink346009453/                                                                                                                                               
2018/09/04 21:13:34  info unpack rootfs: /tmp/umoci-TestUnpackManifestCustomLayer_bundle983864386/rootfs                                                                  
2018/09/04 21:13:34  info unpack layer: sha256:159fc03d42b1eb2588cdffaabe13b9a4b25879d64db0ea473c6c411adcc5740a                                                          
2018/09/04 21:13:34  warn xatt{.} ignoring ENOTSUP on setxattr "user.rootlesscontainers"                                                                                  
2018/09/04 21:13:34  warn xatt{test_file} ignoring ENOTSUP on setxattr "user.rootlesscontainers"                                                                         
2018/09/04 21:13:34  warn rootless{rootfs/} ignoring forbidden xattr: "security.selinux"     
2018/09/04 21:13:34  warn xatt{test_dir} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
2018/09/04 21:13:34  warn rootless{rootfs/} ignoring forbidden xattr: "security.selinux"                                                                       
2018/09/04 21:13:34  info unpack layer: sha256:29788ced4c99508cba36d0a32e9029789641b2996dbead688cc114fc7203cd9c
2018/09/04 21:13:34  warn xatt{.} ignoring ENOTSUP on setxattr "user.rootlesscontainers"                                                                                  
2018/09/04 21:13:34  warn xatt{test_script.sh} ignoring ENOTSUP on setxattr "user.rootlesscontainers"                                                          
2018/09/04 21:13:34  warn rootless{rootfs/} ignoring forbidden xattr: "security.selinux"                
FAIL                                                                                                           
FAIL    github.com/openSUSE/umoci/oci/layer     0.089s
```

**Comment by cyphar** [comment] 2018-09-05 04:55
That's not good -- somehow we generated a layer that contains `security.selinux` (which shouldn't happen) and so now `umoci` freaks out when being asked to extract a `security.selinux` xattr (which is a good thing overall but is a bit of an issue).

Also I think maybe we shouldn't warn for *every* `security.selinux` entry because the entire filesystem would contain those if you are running on an SELinux-configured system...

**Comment by cyphar** [comment] 2018-09-10 17:16
Okay, I played around with `umoci` on Fedora. The basic issue is that we are attempting to restore the parent directory's metadata (which includes the `security.selinux` extended attribute -- and thus `umoci` freaks out). One option would be to special-case this, but I think a much simpler solution is going to be to only ever do `Lsetxattr` if the value of the `xattr` is different.

**Comment by cyphar** [comment] 2018-09-10 17:40
According to my testing in a Fedora 28 VM, #259 should fix all of the `go test` errors (as well as fixing the issues with actually using `umoci` on Fedora with `setenforce 1`).

**Closed as completed** 2018-09-11 02:19 UTC

**Comment by ganto** [comment] 2018-09-11 05:46
@cyphar Just tested with `umoci-0.4.2` works for me now. Thanks a lot :+1:

**Comment by cyphar** [comment] 2018-09-11 06:50
No problem, sorry for taking so long on this issue. :P
